### ISSUE TITLE
temporal-k8s app not reacting to changes in relation with PostgresQL

### ISSUE THREAD

**Issue by Osama-Kassem** [canonical/temporal-k8s-operator#46]
### Bug Description

IS manages a temporal deployment with multiple units of frontend, history, matching, and worker units. This is connected to a PostgresQL VM charm with 2 units only. One of them being the leader (read+write), and the other being a read-only replica.

It seems that at some point in the past (>1 week, so we can't verify theory using patroni logs), the leader unit of postgres switched. All temporal k8s apps received this change in their relations (`juju show-unit` verifies that), but not all units updated their pebble plan with the correct configurations. The temporal-k8s-history is still sending requests to the read only replica.

This results in quite a lot of errors, namely the frontend or tctl not showing new workflows, and workflows not being retried.

### To Reproduce

Incredibly hard to reproduce, especially given that some temporal-k8s apps were updated just fine.

### Environment

Juju 3.5 deployed on MicroK8s. Temporal-k8s apps are all on `latest/edge`. Database is a VM charm.

### Relevant log output

```shell
Will have IS update this.
```

**Comment by mcarvalhor** [comment]
Hi 👋

### Relevant log output
Juju status from Temporal: https://pastebin.canonical.com/p/b6C5Y4hDxn/
Juju status from PostgreSQL database: https://pastebin.canonical.com/p/Xy2v5S92hz/ (primary: 10.141.113.39)
Juju show-unit and pebble plan of working unit: https://pastebin.canonical.com/p/s9ZNYb4tRJ/
Juju show-unit and pebble plan of broken unit: https://pastebin.canonical.com/p/RNB9tKXxJM/

**Comment by mcarvalhor** [comment]
Not sure if it's the root cause of the issue, but I noticed that the **temporal-k8s** unit (the working one) has a `peers` relation (with itself) in which it is providing the wrong IP address of the database for the visibility DB:
https://pastebin.canonical.com/p/s9ZNYb4tRJ/
```
  - relation-id: 39
    endpoint: peer
    related-endpoint: peer
    application-data:
      database_connections: '{"db": {"dbname": "temporal-k8s_db", "host": "10.141.113.39",
        "port": "5432", "password": "REDACTED", "user": "relation-45", "tls":
        true}, "visibility": {"dbname": "temporal-k8s_visibility", "host": "10.141.113.44",
        "port": "5432", "password": "REDACTED", "user": "relation-44", "tls":
        true}}'
      num_history_shards: "2048"
      openfga: '{"store_id": "REDACTED", "token": "REDACTED",
        "address": "10.152.183.220", "port": 8080, "scheme": "http", "auth_model_id":
        "REDACTED"}'
      schema_ready: "true"
```
